# Generated by Django 5.0.6 on 2024-09-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_itenscompra"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="autor",
            field=models.ManyToManyField(related_name="livros", to="core.autor"),
        ),
    ]
